(function initAtelaCopy() {
  const COPY = {
    ko: {
      page: {
        title: 'ATELA · 한국어가 깨지지 않는 AI 크리에이티브 플랫폼',
        description: '한국어 텍스트와 브랜드 디테일을 보존하는 AI 크리에이티브 플랫폼. 스토어 연결, 자동 생성, 전문가 매칭을 한 곳에서.',
      },
      nav: {
        login: '로그인',
        cta: '무료로 시작하기',
      },
      hero: {
        titleLead: '이커머스 · 브랜드를 위한',
        titlePrefix: '단 하나의',
        titleHighlight: '비주얼 솔루션',
        subtitleLines: [
          'Cafe24, Shopify, URL 상품 데이터를 ATELA에 연결하면',
          '하나의 소스가 스튜디오, 디테일, 라이프스타일, 영상까지 확장됩니다.',
        ],
        cta: '무료로 시작하기',
        packAriaPrefix: '결과 보기',
      },
      heroDemo: {
        packs: {
          drg: {
            name: 'Dr.G 크림',
            sourceAlt: 'Dr.G 크림 상품 소스',
            outputs: {
              studio: 'Dr.G 크림 Background 결과물',
              angle: 'Dr.G 크림 Lighting 결과물',
              variation: 'Dr.G 크림 Variation 결과물',
              lifestyle: 'Dr.G 크림 Angle 결과물',
            },
            videoAlt: 'Dr.G 크림 영상 결과물',
          },
          chamo: {
            name: 'CHAMO 핸드크림',
            sourceAlt: 'CHAMO 핸드크림 상품 소스',
            outputs: {
              studio: 'CHAMO 핸드크림 Background 결과물',
              angle: 'CHAMO 핸드크림 Lighting 결과물',
              variation: 'CHAMO 핸드크림 Variation 결과물',
              lifestyle: 'CHAMO 핸드크림 Angle 결과물',
            },
            videoAlt: 'CHAMO 핸드크림 영상 결과물',
          },
          lamp: {
            name: '테이블 램프',
            sourceAlt: '테이블 램프 상품 소스',
            outputs: {
              studio: '테이블 램프 Background 결과물',
              angle: '테이블 램프 Lighting 결과물',
              variation: '테이블 램프 Variation 결과물',
              lifestyle: '테이블 램프 Angle 결과물',
            },
          },
          sofa: {
            name: '커브드 소파',
            sourceAlt: '커브드 소파 상품 소스',
            outputs: {
              studio: '커브드 소파 Background 결과물',
              angle: '커브드 소파 Lighting 결과물',
              variation: '커브드 소파 Variation 결과물',
              lifestyle: '커브드 소파 Angle 결과물',
            },
          },
          jacket: {
            name: '마운틴 자켓',
            sourceAlt: '마운틴 자켓 상품 소스',
            outputs: {
              studio: '마운틴 자켓 Background 결과물',
              angle: '마운틴 자켓 Lighting 결과물',
              variation: '마운틴 자켓 Variation 결과물',
              lifestyle: '마운틴 자켓 Angle 결과물',
            },
          },
          pilot_trunk: {
            name: '파일럿 트렁크',
            sourceAlt: '파일럿 트렁크 상품 소스',
            outputs: {
              studio: '파일럿 트렁크 Background 결과물',
              angle: '파일럿 트렁크 Lighting 결과물',
              variation: '파일럿 트렁크 Variation 결과물',
              lifestyle: '파일럿 트렁크 Angle 결과물',
            },
            videoAlt: '파일럿 트렁크 영상 결과물',
          },
        },
      },
      logoCloud: {
        title: 'Trusted by',
        ariaLabel: 'Trusted by brand logos',
      },
      stats: {
        items: [
          { n: '98.2%', l: '한글 렌더링 정확도', s: '내부 10K 샘플' },
          { n: '4분', l: '신상 → 50장', s: 'Webhook 동기화' },
          { n: '199명', l: 'AI 전문가 풀', s: '6개 분야' },
          { n: '48h', l: '평균 납품', s: '프로젝트 turnaround' },
        ],
      },
      tech: {
        eyebrow: 'TECH · TEXT & DETAIL PRESERVATION',
        titleLines: ['한글과 디테일이 무너지면', '상품 페이지가 아닙니다.'],
        lede: '상품 이미지는 그럴듯해 보이는 것만으로는 충분하지 않습니다. 브랜드 카피, 로고, 자수, 제품 각인, 패키지의 작은 텍스트처럼 구매를 좌우하는 디테일까지 정확하게 살아 있어야 합니다. ',
        ledeStrong: 'ATELA는 브랜드 자산과 제품 디테일을 끝까지 선명하게 유지하는 결과',
        cta: '기술 백서 다운로드 ↓',
        footnote: '한글 카피 · 브랜드 로고 · 제품 각인 · 소재 디테일 비교',
        comparisons: [
          {
            id: 'nb2',
            brandLines: ['Nanobanana Pro'],
            eyebrow: '',
            image: '/assets/comparisons/1/nb2.avif',
            mainPosition: '50% 52%',
            detailSide: 'left',
            notePrefix: 'Nanobanana Pro.',
            note: '장면은 그럴듯해도 한글 배너, 브랜드 로고, 텀블러 각인처럼 구매에 영향을 주는 작은 정보는 흔들리기 쉽습니다.',
            details: [
              { position: '37% 47%', scale: 10, alt: 'Nanobanana Pro tumbler logo detail' },
              { position: '71% 54%', scale: 12, alt: 'Nanobanana Pro jacket detail' },
            ],
          },
          {
            id: 'atela',
            brandLines: ['ATELA'],
            eyebrow: 'DETAIL PRESERVED',
            image: '/assets/comparisons/1/atela.avif',
            mainPosition: '50% 48%',
            detailSide: 'right',
            notePrefix: 'ATELA.',
            note: 'ATELA는 한글 배너, 로고, 자수, 각인처럼 브랜드 신뢰를 만드는 작은 정보까지 또렷하게 유지하는 결과에 집중합니다.',
            details: [
              { position: '100% 78%', scale: 3.5, alt: 'ATELA tumbler logo detail' },
              { position: '40% 98%', scale: 5, alt: 'ATELA jacket engraving detail' },
            ],
          },
        ],
      },
      compound: {
        eyebrow: 'SYSTEM LEARNING LOOP',
        headlineLead: 'Built to compound.',
        headlineEmphasis: 'A system that never stops learning.',
        sub: 'Every ATELA project feeds the system. Performance signals, approved outputs, and channel feedback shape what gets made next. The more your team runs, the sharper the next batch becomes.',
        briefTitle: '봄 런칭 캠페인',
        briefCopy: '세럼 SKU 24개, Meta·Naver·29CM 버전 제작',
        labels: {
          creative: 'Creative',
          v1: 'V1 — New Creative',
          distribution: 'Distribution Channels',
          performance: 'Performance Data',
          variants: 'Optimized Variants',
          training: 'Model Training',
          ideation: 'Ideation Engine',
        },
        channelCards: [
          { title: 'Meta Ad', desc: '하나의 브리프를 즉시 광고 시안으로.', glyph: 'AD', tone: 'pink' },
          { title: 'Social UGC', desc: '리뷰 문법으로 자연스럽게 변주.', glyph: 'UGC', tone: 'blue' },
          { title: 'PDP', desc: '성과 데이터가 상세페이지를 다시 다듬습니다.', glyph: 'PDP', tone: 'lime' },
          { title: 'Display', desc: '캠페인을 배너 규격으로 빠르게 확장.', glyph: 'OOH', tone: 'sand' },
          { title: 'Short-form', desc: '승인된 방향을 숏폼 영상으로 전개.', glyph: 'REEL', tone: 'violet' },
          { title: 'Marketplace', desc: '채널별 비주얼 세트를 자동 분기.', glyph: 'SKU', tone: 'ink' },
        ],
        modelCards: [
          { title: 'Custom Model', desc: '브랜드 룩과 카피 패턴을 계속 축적합니다.', icon: 'model' },
          { title: 'Custom Agent', desc: '다음 배치와 다음 변주를 자동으로 제안합니다.', icon: 'agent' },
        ],
        mobileCards: [
          { title: 'Creative', body: '하나의 브리프가 메타, 상세, 쇼핑, 숏폼 버전으로 퍼집니다.' },
          { title: 'Performance Data', body: 'CTR, ROAS, 채널별 반응 데이터가 다음 변주에 반영됩니다.' },
          { title: 'Model Training', body: '승인된 브랜드 룩과 텍스트 패턴이 누적되어 다음 배치가 더 날카로워집니다.' },
          { title: 'Output', body: 'YOUR NEXT CREATIVE IS DATA INFORMED AND AGENT ASSISTED.' },
        ],
      },
      integrations: {
        eyebrow: 'WORKFLOW FOR ECOMMERCE BRANDS',
        titlePrefix: '카탈로그에 필요한',
        titleHighlight: '모든 비주얼을',
        titleSuffix: ', 한번에.',
        ledeLines: [
          '카탈로그 전체의 비주얼 퀄리티와 완성도를 끌어올리세요.',
        ],
        bullets: [
          { k: '01', title: '워크플로우 선택', body: '지금 필요한 비주얼 작업 유형부터 고르고, 해당 결과를 바로 확인합니다.' },
          { k: '02', title: '결과 먼저 정렬', body: '가운데 이미지 한 장으로 톤, 구도, 채널 적합성을 빠르게 맞춥니다.' },
          { k: '03', title: '운영 효과 연결', body: '우측 KPI로 전환율, 갱신 속도, 캠페인 리드타임 같은 운영 임팩트를 함께 읽습니다.' },
        ],
        proofTags: ['팩샷', '옵션 컷', '인포그래픽'],
        cta: '워크플로우 더 보기 →',
        selectorEyebrow: '비주얼 과제',
        selectorBadge: '좌측 선택 / 가운데 결과 / 우측 KPI',
        selectorAriaLabel: '워크플로우 과제 선택',
        metricAriaLabel: '워크플로우 성과 지표',
        challenges: [
          {
            id: 'packshot',
            k: '01',
            label: '일관된 팩샷',
            short: '대표컷 톤과 구도를 SKU 전체에 맞춰 정렬',
            kicker: 'CONSISTENT PACKSHOT',
            title: 'SKU별 대표 팩샷 정렬',
            body: '카탈로그 전반의 대표컷 톤, 배경, 구도를 일정하게 맞춰 상품군을 한눈에 정리합니다.',
            image: '/assets/workflow/consistent-packshot.jpg',
            alt: '일관된 팩샷 예시 이미지',
          },
          {
            id: 'staging',
            k: '02',
            label: '제품 연출컷',
            short: '팩샷을 라이프스타일 장면으로 확장',
            kicker: 'PRODUCT STAGING',
            title: '제품 연출컷 생성',
            body: '밋밋한 제품 컷을 실제 사용 장면처럼 확장해 공간감과 맥락을 함께 전달합니다.',
            image: '/assets/workflow/product-staging.jpg',
            alt: '제품 연출컷 예시 이미지',
          },
          {
            id: 'lighting',
            k: '03',
            label: '조명 제어',
            short: '같은 제품 컷도 채널 톤에 맞게 재조정',
            kicker: 'LIGHTING CONTROL',
            title: '조명 톤 정렬',
            body: '같은 제품 컷에서도 조명 분위기와 그림자 방향을 조절해 브랜드 톤을 더 안정적으로 맞춥니다.',
            image: '/assets/workflow/lighting-control.jpg',
            alt: '조명 제어 예시 이미지',
          },
          {
            id: 'closeups',
            k: '04',
            label: '디테일 확대컷',
            short: '질감과 마감 포인트를 근접 컷으로 분리',
            kicker: 'CLOSE-UPS',
            title: '구매 포인트 확대컷',
            body: '구매 결정에 필요한 질감, 마감, 핵심 부위를 근접 컷으로 분리해 신뢰도를 높입니다.',
            image: '/assets/workflow/close-ups.jpg',
            alt: '디테일 확대컷 예시 이미지',
          },
          {
            id: 'infographics',
            k: '05',
            label: '제품 인포그래픽',
            short: '핵심 기능과 구매 포인트를 한 장에서 설명',
            kicker: 'PRODUCT INFOGRAPHICS',
            title: '텍스트 포함 인포그래픽',
            body: '핵심 기능과 차별점을 텍스트 오버레이와 함께 정리해 상세페이지 이해도를 높입니다.',
            image: '/assets/workflow/product-infographics.jpg',
            alt: '제품 인포그래픽 예시 이미지',
          },
          {
            id: 'dimensions',
            k: '06',
            label: '치수 오버레이',
            short: '가구, 리빙 상품의 크기 정보를 이미지 위에 표시',
            kicker: 'DIMENSION OVERLAYS',
            title: '치수 정보 오버레이',
            body: '치수와 비율 정보를 제품 위에 바로 얹어, 가구와 리빙 상품의 판단을 더 쉽게 만듭니다.',
            image: '/assets/workflow/dimension-overlays.jpg',
            alt: '치수 오버레이 예시 이미지',
          },
          {
            id: 'swap',
            k: '07',
            label: '제품 교체',
            short: '같은 장면과 구도 안에서 SKU만 빠르게 교체',
            kicker: 'PRODUCT SWAP',
            title: '같은 장면 안의 SKU 교체',
            body: '같은 장면과 카메라 구도 안에서 제품만 교체해 SKU 배치를 훨씬 빠르게 확장합니다.',
            image: '/assets/workflow/product-swap.jpg',
            alt: '제품 교체 예시 이미지',
          },
          {
            id: 'motion',
            k: '08',
            label: '이미지 기반 영상화',
            short: '정지 이미지를 짧은 모션으로 확장',
            kicker: 'IMAGE TO VIDEO',
            title: '정지 이미지를 짧은 모션으로',
            body: '정지 이미지를 짧은 영상으로 확장해 광고나 숏폼 소재까지 자연스럽게 이어집니다.',
            image: '/assets/workflow/image-to-video.jpg',
            alt: '이미지 기반 영상화 예시 이미지',
          },
          {
            id: 'spin',
            k: '09',
            label: '360도 회전 뷰',
            short: '단일 제품을 회전 시점으로 보여주는 기본 뷰',
            kicker: '360 SPINS',
            title: '회전 뷰로 구조 전달',
            body: '단일 제품을 회전 뷰로 보여줘 실루엣과 구조를 더 입체적으로 전달합니다.',
            image: '/assets/workflow/spins-360.jpg',
            alt: '360도 회전 뷰 예시 이미지',
          },
        ],
        metrics: [
          {
            value: '+20%',
            label: '전환율 상승',
            body: '풍부한 비주얼 콘텐츠로 평균 전환율 상승',
          },
          {
            value: '10x',
            label: '카탈로그 리프레시 속도',
            body: '더 빠른 카탈로그 리프레시',
          },
          {
            value: '90%',
            label: '시즌 캠페인 리드타임 단축',
            body: '시즌 캠페인 출시 시간 단축',
          },
        ],
        outputRailLabel: '워크플로우 출력 유형',
        outputTags: ['팩샷', '연출컷', '옵션 컷', '확대컷', '인포그래픽', '모션'],
        selectorFootnote: '왼쪽에서 과제를 선택하면, 가운데 결과 예시와 우측 운영 KPI를 함께 보며 우선순위를 정할 수 있습니다.',
        selectorCallout: 'result-first workflow',
      },
      showcase: {
        eyebrow: 'SHOWCASE · EXPERT HOOK',
        titleLines: ['이런 컨텐츠 만들고 싶은데,', '막막하신가요?'],
        galleryLabel: 'ATELA 작업 예시 갤러리',
        cards: [
          {
            id: 'pdp',
            size: 'hero',
            kicker: 'PDP REFRESH',
            accentLabel: 'TEXT SAFE',
            accent: '#C6FF3D',
            title: '상세페이지 리프레시',
            body: '한글 카피와 제품 디테일을 살린 대표 상세 컷 구성을 빠르게 정리합니다.',
            image: '/assets/hero-demo/drg/bg.avif',
            alt: 'ATELA product detail page refresh showcase',
            tags: ['PDP', '상세', '브랜드 디테일'],
          },
          {
            id: 'ads',
            size: 'side',
            kicker: 'PERFORMANCE ADS',
            accentLabel: 'CTR READY',
            accent: '#FF3DA8',
            title: '광고 크리에이티브',
            body: 'Meta · TikTok 캠페인용 성과형 배리에이션을 빠르게 제작합니다.',
            image: '/assets/hero-demo/chamo/bg.avif',
            alt: 'ATELA performance ad creative showcase',
            tags: ['Ads', 'A/B Test', 'Campaign'],
          },
          {
            id: 'lifestyle',
            size: 'side',
            kicker: 'LIFESTYLE VISUAL',
            accentLabel: 'BRAND MOOD',
            accent: '#6B3DFF',
            title: '라이프스타일 쇼케이스',
            body: '브랜드 무드를 유지한 채 상품을 더 매력적으로 보여주는 장면 컷입니다.',
            image: '/assets/hero-demo/lamp/bg.avif',
            alt: 'ATELA lifestyle commerce showcase',
            tags: ['Lifestyle', 'Mood', 'Campaign'],
          },
          {
            id: 'motion',
            size: 'wide',
            kicker: 'MOTION / VIDEO',
            accentLabel: 'LAUNCH PACK',
            accent: '#FFB020',
            title: '숏폼 · 모션 패키지',
            body: '런칭, 리타겟팅, 상세 하단 모듈까지 이어지는 짧은 영상 소재를 함께 만듭니다.',
            image: '/assets/hero-demo/pilot_trunk/bg.avif',
            alt: 'ATELA motion and video showcase',
            tags: ['Motion', 'Reels', 'Video'],
          },
        ],
        footnote: '좋아 보이는 포맷을 고르면, ATELA가 해당 분야 전문가를 프로젝트 단위로 매칭합니다.',
        footCallout: '프로젝트 단위 · 락인 없음',
      },
      marketplace: {
        eyebrow: 'EXPERT MARKETPLACE',
        titlePrefix: 'AI 전문가가 필요한 순간,',
        titleHighlight: 'on-demand',
        titleSuffix: '로.',
        lede: 'Product Visual과 Instagram Ads는 전혀 다른 분야입니다. ATELA는 프로젝트 유형에 맞는 AI 크리에이터를 자동 매칭하고, 브랜드 컨텍스트는 플랫폼이 넘겨줍니다. ',
        ledeStrong: '6개월 락인, 없습니다.',
        countLabelSuffix: '명',
        availability: 'available',
        projectsSuffix: 'projects',
        rateSuffix: '/ 프로젝트',
        railHeading: '',
        railCount: '',
        railCta: '전체 리스트 →',
        specialties: [
          { k: '01', title: 'Performance Creative', desc: 'Meta·TikTok·카카오 광고. CTR 기반 iteration.', tags: ['광고', 'A/B test'], color: '#FF3DA8', count: 42 },
          { k: '02', title: 'Product Visual', desc: '상세페이지, 모델 샷, 누끼. 채널 규격 숙련.', tags: ['누끼', '상세'], color: '#C6FF3D', count: 68 },
          { k: '03', title: 'Instagram / Reels', desc: '15초 Reels, 카루셀. Gen Z 톤 전문.', tags: ['Reels', '숏폼'], color: '#6B3DFF', count: 31 },
          { k: '04', title: 'Brand Campaign', desc: '시즌 캠페인, lookbook, editorial.', tags: ['Editorial'], color: '#E8D5B0', count: 24 },
          { k: '05', title: 'Motion / Video', desc: 'Product motion, TVC, 3D product.', tags: ['Motion', '3D'], color: '#FFB020', count: 19 },
          { k: '06', title: 'Localization', desc: '일본·미국·동남아 현지화 AI 디자이너.', tags: ['JP', 'US', 'SEA'], color: '#3DA8FF', count: 15 },
        ],
        flow: [
          { step: '1', title: '브리프 업로드', body: '상품 · 채널 · 톤 · 예산. 2분.' },
          { step: '2', title: 'AI 매칭 3명 추천', body: '전문 분야 · 과거 성과 · 가용성 기반.' },
          { step: '3', title: '프로젝트 단위 진행', body: '브랜드 에셋·가이드는 ATELA가 자동 전달.' },
          { step: '4', title: '48시간 내 납품', body: '평균 turnaround. 수정 무제한.' },
        ],
        motionPills: [
          '광고 크리에이티브',
          '소셜 콘텐츠',
          '영상 제작',
          '사진 촬영',
          '모션 그래픽',
          '프레젠테이션',
          '웹·UI 디자인',
          'OOH·페이크 OOH',
          '일러스트',
          '이메일 디자인',
          '브랜드 전략',
          '3D 디자인',
          '카피라이팅',
          'AI 컨설팅',
          '캠페인 기획',
          'AI 확장형 크리에이티브',
          '그 외 다수',
        ],
        experts: [
          { n: '이수현', h: '수', r: 4.9, proj: 127, spec: 'Performance · Beauty', rate: '48만원~', color: '#FF3DA8' },
          { n: '박준호', h: '준', r: 4.8, proj: 89, spec: 'Product Visual · F&B', rate: '36만원~', color: '#C6FF3D' },
          { n: 'Jiwon K.', h: 'J', r: 5.0, proj: 64, spec: 'Motion · Fashion', rate: '72만원~', color: '#6B3DFF' },
          { n: '최민아', h: '민', r: 4.9, proj: 156, spec: 'Reels · Gen Z Brand', rate: '54만원~', color: '#E8D5B0' },
        ],
      },
      compare: {
        eyebrow: 'WHY ATELA',
        titlePrefix: '인하우스도, 에이전시도, 프리랜서도 아닌',
        titleHighlight: '새로운 옵션.',
        dims: ['Speed', 'Flexibility', 'Quality', 'Scalability', 'Efficiency', 'Strategy'],
        rows: [
          { n: 'ATELA', d: 'AI 도구 + 전문가 매칭을 한 플랫폼에서.', v: [1, 1, 1, 1, 1, 1], on: true },
          { n: 'In-house Team', d: '인하우스 디자이너. 스킬·역량 한정.', v: [0, 1, 1, 0, 0, 0] },
          { n: 'Creative Agency', d: '에이전시 계약. 느리고 비싸고 경직됨.', v: [0, 0, 1, 0, 0, 0] },
          { n: 'Freelancer', d: '프리랜서. 품질 편차 · 스케일 어려움.', v: [0, 1, 0, 0, 0, 0] },
          { n: 'AI Tools only', d: 'MJ · DALL·E. 브랜드 context 없음.', v: [1, 0, 0, 1, 1, 0] },
        ],
      },
      caseStudy: {
        badge: '뷰티 브랜드 · 무신사',
        eyebrow: 'CASE STUDY · 뷰티 브랜드 A',
        titlePrefix: '촬영 0회, 시즌 컬렉션',
        titleHighlight: '런칭.',
        body: '신상 1개당 3일의 촬영·리터치가 필요했던 팀. Cafe24 연동 + ATELA Growth 도입 후, 상세페이지 35장을 평균 14분에 생성하고, Performance Creative는 주 2회씩 AI 전문가와 iteration. 주간 신상 업로드 4종 → 28종으로 증가.',
        quote: '촬영팀 없이 시즌 캠페인을 돌려요. 브랜드 톤은 오히려 더 일관됐어요. 광고 크리에이티브만 외부 전문가랑 돌리고, 나머지는 우리가 플랫폼에서.',
        cite: '브랜드 매니저, A사',
        stats: [
          { value: '82%', label: '촬영비 절감' },
          { value: '7×', label: '주간 업로드' },
          { value: '+38%', label: '광고 CTR' },
        ],
        cta: '전체 사례 보기 →',
      },
      pricing: {
        eyebrow: 'PRICING',
        title: 'Starter에서 Business까지, Annual은 더 저렴하게.',
        billingAriaLabel: '결제 주기 선택',
        billingMonthly: '월간',
        billingAnnual: '연간',
        billingBadge: '30% OFF',
        toolsTiers: [
          {
            name: 'Starter',
            features: ['월 200 credits', '선택 모델만 사용', '이미지 4개 병렬 생성', '기본 워크플로우'],
            prices: {
              monthly: { prefix: '₩', amount: '29,000', suffix: '/월', note: '기본가' },
              annual: { prefix: '₩', amount: '29,000', suffix: '/월', note: '연간 동일가' },
            },
          },
          {
            name: 'Creator',
            features: ['월 1,000 credits', '모든 모델 사용', '이미지 8개 병렬 생성', '선호 모델 365일 무제한'],
            prices: {
              monthly: { prefix: '₩', amount: '59,000', suffix: '/월', note: '월 단위 결제' },
              annual: { prefix: '₩', amount: '39,000', suffix: '/월', originalAmount: '59,000', note: '연간 결제 기준' },
            },
          },
          {
            name: 'Growth',
            badge: 'Most Popular',
            features: ['월 3,000 credits', '모든 모델 + 우선 처리', 'API · 커스텀 프리셋', '비디오 모델 1개 무제한'],
            prices: {
              monthly: { prefix: '₩', amount: '129,000', suffix: '/월', note: '월 단위 결제' },
              annual: { prefix: '₩', amount: '99,000', suffix: '/월', originalAmount: '129,000', note: '연간 결제 기준' },
            },
            dark: true,
            featured: true,
          },
          {
            name: 'Business',
            badge: 'Best Value',
            features: ['좌석당 월 1,500 credits', '2-15명 공용 워크스페이스', '공유 크레딧 풀', '우선 지원 · 사용량 분석'],
            prices: {
              monthly: { prefix: '₩', amount: '89,000', suffix: '/좌석/월', note: '2석부터' },
              annual: { prefix: '₩', amount: '59,000', suffix: '/좌석/월', originalAmount: '89,000', note: '2석부터 · 연간 결제' },
            },
          },
        ],
        marketTitle: 'AI 전문가가 필요하신가요?',
        marketSubtitle: '필요할 때만 꺼내 쓰는 비장의 무기.',
        marketRows: [
          { label: 'Performance Creative', value: '48만원~' },
          { label: 'PDP Refresh (상세 1건)', value: '36만원~' },
          { label: 'Instagram Reels 15s', value: '54만원~' },
          { label: 'Lookbook Sprint (20컷)', value: '120만원~' },
          { label: 'Motion · Video', value: '72만원~' },
        ],
        guarantee: '고정 견적 · 빠른 납기',
        subnote: '리테이너 없음 · 락인 없음',
      },
      finalCta: {
        eyebrow: 'START TODAY',
        titleLines: ['오늘 상품 연결,', '내일 아침 50장\n+ 전문가 매칭.'],
        body: '지금 무료로 시작하세요.',
        primaryCta: '무료로 시작하기 →',
        secondaryCta: '세일즈에 문의 ↗',
      },
      footer: {
        description: '한국어가 깨지지 않는 AI 크리에이티브 플랫폼. Yonsei Univ. CV Lab 출신 팀. Seoul, South Korea.',
        platformTitle: '플랫폼',
        platformLinks: {
          tech: 'Korean AI',
          integrations: '워크플로우',
          marketplace: '전문가',
        },
        companyTitle: '회사',
        companyLinks: ['소개', '팀 · 연구', '블로그', '채용'],
        supportTitle: '지원',
        supportLinks: ['문서 · API', '커뮤니티', '문의', '서비스 상태'],
        bottomLeft: '© 2026 ATELA Inc. · 사업자 000-00-00000',
        bottomRight: '이용약관 · 개인정보처리방침 · 쿠키',
      },
    },
    en: {
      page: {
        title: 'ATELA · AI Creative Platform That Preserves Text and Brand Detail',
        description: 'AI creative platform for ecommerce teams. Preserve text and brand detail, connect your catalog, automate outputs, and match with experts on demand.',
      },
      nav: {
        login: 'Log in',
        cta: 'Start trial',
      },
      hero: {
        titleLead: 'For ecommerce brands',
        titlePrefix: 'A single',
        titleHighlight: 'visual solution',
        subtitleLines: [
          'Connect Cafe24, Shopify, or product URLs to ATELA,',
          'and one source expands into studio, detail, lifestyle, and video outputs.',
        ],
        cta: 'Start trial',
        packAriaPrefix: 'View results for',
      },
      heroDemo: {
        packs: {
          drg: {
            name: 'Dr.G Cream',
            sourceAlt: 'Dr.G cream source asset',
            outputs: {
              studio: 'Dr.G cream background output',
              angle: 'Dr.G cream lighting output',
              variation: 'Dr.G cream variation output',
              lifestyle: 'Dr.G cream angle output',
            },
            videoAlt: 'Dr.G cream video output',
          },
          chamo: {
            name: 'CHAMO Hand Cream',
            sourceAlt: 'CHAMO hand cream source asset',
            outputs: {
              studio: 'CHAMO hand cream background output',
              angle: 'CHAMO hand cream lighting output',
              variation: 'CHAMO hand cream variation output',
              lifestyle: 'CHAMO hand cream angle output',
            },
            videoAlt: 'CHAMO hand cream video output',
          },
          lamp: {
            name: 'Table Lamp',
            sourceAlt: 'Table lamp source asset',
            outputs: {
              studio: 'Table lamp background output',
              angle: 'Table lamp lighting output',
              variation: 'Table lamp variation output',
              lifestyle: 'Table lamp angle output',
            },
          },
          sofa: {
            name: 'Curved Sofa',
            sourceAlt: 'Curved sofa source asset',
            outputs: {
              studio: 'Curved sofa background output',
              angle: 'Curved sofa lighting output',
              variation: 'Curved sofa variation output',
              lifestyle: 'Curved sofa angle output',
            },
          },
          jacket: {
            name: 'Mountain Jacket',
            sourceAlt: 'Mountain jacket source asset',
            outputs: {
              studio: 'Mountain jacket background output',
              angle: 'Mountain jacket lighting output',
              variation: 'Mountain jacket variation output',
              lifestyle: 'Mountain jacket angle output',
            },
          },
          pilot_trunk: {
            name: 'Pilot Trunk',
            sourceAlt: 'Pilot trunk source asset',
            outputs: {
              studio: 'Pilot trunk background output',
              angle: 'Pilot trunk lighting output',
              variation: 'Pilot trunk variation output',
              lifestyle: 'Pilot trunk angle output',
            },
            videoAlt: 'Pilot trunk video output',
          },
        },
      },
      logoCloud: {
        title: 'Trusted by',
        ariaLabel: 'Trusted by brand logos',
      },
      stats: {
        items: [
          { n: '98.2%', l: 'Hangul render accuracy', s: 'Internal 10K sample' },
          { n: '4 min', l: 'New launch → 50 images', s: 'Webhook sync' },
          { n: '199', l: 'AI expert network', s: '6 specialties' },
          { n: '48h', l: 'Average delivery', s: 'Project turnaround' },
        ],
      },
      tech: {
        eyebrow: 'TECH · TEXT & DETAIL PRESERVATION',
        titleLines: ['If text and detail break,', "it's not a product page."],
        lede: 'A product image cannot just look good. Brand copy, logos, embroidery, engravings, and packaging text all influence purchase decisions, and they need to stay intact. ',
        ledeStrong: 'ATELA focuses on outputs that preserve brand assets and product detail all the way through.',
        cta: 'Download technical brief ↓',
        footnote: 'Hangul copy · brand logos · engravings · material-detail comparison',
        comparisons: [
          {
            id: 'nb2',
            brandLines: ['Nanobanana Pro'],
            eyebrow: '',
            image: '/assets/comparisons/1/nb2.avif',
            mainPosition: '50% 52%',
            detailSide: 'left',
            notePrefix: 'Nanobanana Pro.',
            note: 'Even when the scene looks convincing, small details that drive conversion, like Hangul banners, brand logos, and product engravings, tend to drift.',
            details: [
              { position: '78% 58%', scale: 3.35, alt: 'Nanobanana Pro jacket logo detail' },
              { position: '31% 47%', scale: 3.05, alt: 'Nanobanana Pro tumbler detail' },
            ],
          },
          {
            id: 'atela',
            brandLines: ['ATELA'],
            eyebrow: 'DETAIL PRESERVED',
            image: '/assets/comparisons/1/atela.avif',
            mainPosition: '50% 48%',
            detailSide: 'right',
            notePrefix: 'ATELA.',
            note: 'ATELA is built to keep the small details that create brand trust, from Hangul banners and logos to embroidery and engravings, crisp and intact.',
            details: [
              { position: '39% 84%', scale: 3.2, alt: 'ATELA jacket logo detail' },
              { position: '91% 60%', scale: 3.1, alt: 'ATELA tumbler engraving detail' },
            ],
          },
        ],
      },
      compound: {
        eyebrow: 'SYSTEM LEARNING LOOP',
        headlineLead: 'Built to compound.',
        headlineEmphasis: 'A system that never stops learning.',
        sub: 'Every ATELA project feeds the system. Performance signals, approved outputs, and channel feedback shape what gets made next. The more your team runs, the sharper the next batch becomes.',
        briefTitle: 'Spring launch campaign',
        briefCopy: '24 serum SKUs, versions for Meta, Naver, and 29CM',
        labels: {
          creative: 'Creative',
          v1: 'V1 — New Creative',
          distribution: 'Distribution Channels',
          performance: 'Performance Data',
          variants: 'Optimized Variants',
          training: 'Model Training',
          ideation: 'Ideation Engine',
        },
        channelCards: [
          { title: 'Meta Ad', desc: 'Turn one brief into ad concepts right away.', glyph: 'AD', tone: 'pink' },
          { title: 'Social UGC', desc: 'Remix naturally in the language of reviews.', glyph: 'UGC', tone: 'blue' },
          { title: 'PDP', desc: 'Performance data sharpens the PDP again.', glyph: 'PDP', tone: 'lime' },
          { title: 'Display', desc: 'Expand campaigns into banner formats fast.', glyph: 'OOH', tone: 'sand' },
          { title: 'Short-form', desc: 'Carry approved directions into short-form video.', glyph: 'REEL', tone: 'violet' },
          { title: 'Marketplace', desc: 'Branch visual sets automatically by channel.', glyph: 'SKU', tone: 'ink' },
        ],
        modelCards: [
          { title: 'Custom Model', desc: 'Keep accumulating brand look and copy patterns.', icon: 'model' },
          { title: 'Custom Agent', desc: 'Suggest the next batch and the next variation automatically.', icon: 'agent' },
        ],
        mobileCards: [
          { title: 'Creative', body: 'One brief fans out into Meta, PDP, commerce, and short-form versions.' },
          { title: 'Performance Data', body: 'CTR, ROAS, and channel-response data feed the next iteration.' },
          { title: 'Model Training', body: 'Approved brand looks and text patterns accumulate so the next batch gets sharper.' },
          { title: 'Output', body: 'YOUR NEXT CREATIVE IS DATA INFORMED AND AGENT ASSISTED.' },
        ],
      },
      integrations: {
        eyebrow: 'WORKFLOW FOR ECOMMERCE BRANDS',
        titlePrefix: 'Every catalog visual',
        titleHighlight: 'you need',
        titleSuffix: ', in one workflow.',
        ledeLines: [
          'Enrich and elevate the visual quality of your entire catalog.',
          'ATELA brings packshots, staging, variants, and infographics into one streamlined ecommerce workflow.',
        ],
        bullets: [
          { k: '01', title: 'Choose the workflow', body: 'Start with the visual job you need most and show the relevant output immediately.' },
          { k: '02', title: 'Align on the result', body: 'Use one center image to align on tone, composition, and channel fitness fast.' },
          { k: '03', title: 'Tie it to impact', body: 'Keep conversion, refresh speed, and campaign lead time visible next to the result.' },
        ],
        proofTags: ['Packshots', 'Variants', 'Infographics'],
        cta: 'Explore the workflow →',
        selectorEyebrow: 'VISUAL CHALLENGES',
        selectorBadge: 'left select / center preview / right KPI',
        selectorAriaLabel: 'Workflow challenge selector',
        metricAriaLabel: 'Workflow metrics',
        challenges: [
          {
            id: 'packshot',
            k: '01',
            label: 'Consistent packshot',
            short: 'Align hero-image tone and composition across SKUs',
            kicker: 'CONSISTENT PACKSHOT',
            title: 'Aligned hero packshots by SKU',
            body: 'Keep tone, background, and composition consistent so large catalogs read cleanly at a glance.',
            image: '/assets/workflow/consistent-packshot.jpg',
            alt: 'Consistent packshot sample',
          },
          {
            id: 'staging',
            k: '02',
            label: 'Product staging',
            short: 'Extend packshots into contextual lifestyle scenes',
            kicker: 'PRODUCT STAGING',
            title: 'Contextual staged scenes',
            body: 'Turn plain product shots into lifestyle scenes that add context, mood, and usage cues.',
            image: '/assets/workflow/product-staging.jpg',
            alt: 'Product staging sample',
          },
          {
            id: 'lighting',
            k: '03',
            label: 'Lighting control',
            short: 'Retune the same product shot for different channel moods',
            kicker: 'LIGHTING CONTROL',
            title: 'Lighting and mood alignment',
            body: 'Adjust lighting direction and atmosphere on the same product shot while staying inside brand rules.',
            image: '/assets/workflow/lighting-control.jpg',
            alt: 'Lighting control sample',
          },
          {
            id: 'closeups',
            k: '04',
            label: 'Close-ups',
            short: 'Isolate texture and finish details in tighter crops',
            kicker: 'CLOSE-UPS',
            title: 'Detail-first product crops',
            body: 'Pull tight crops around texture, finish, and important purchase signals to build more trust.',
            image: '/assets/workflow/close-ups.jpg',
            alt: 'Close-up sample',
          },
          {
            id: 'infographics',
            k: '05',
            label: 'Product infographics',
            short: 'Explain key benefits with text overlays in one frame',
            kicker: 'PRODUCT INFOGRAPHICS',
            title: 'Informative product visuals',
            body: 'Combine product visuals with text overlays so features and benefits are readable in one glance.',
            image: '/assets/workflow/product-infographics.jpg',
            alt: 'Product infographic sample',
          },
          {
            id: 'dimensions',
            k: '06',
            label: 'Dimension overlays',
            short: 'Add size and ratio information directly on the image',
            kicker: 'DIMENSION OVERLAYS',
            title: 'Size and proportion overlays',
            body: 'Place dimension cues directly on the image so furniture and home goods are easier to judge quickly.',
            image: '/assets/workflow/dimension-overlays.jpg',
            alt: 'Dimension overlay sample',
          },
          {
            id: 'swap',
            k: '07',
            label: 'Product swap',
            short: 'Swap only the SKU while keeping the same scene and camera',
            kicker: 'PRODUCT SWAP',
            title: 'Scene-stable SKU swaps',
            body: 'Replace just the product inside the same scene and composition to scale batches much faster.',
            image: '/assets/workflow/product-swap.jpg',
            alt: 'Product swap sample',
          },
          {
            id: 'motion',
            k: '08',
            label: 'Image to video',
            short: 'Extend still imagery into short-form motion',
            kicker: 'IMAGE TO VIDEO',
            title: 'Still-to-motion expansion',
            body: 'Turn approved stills into short motion assets that can carry into ads and short-form channels.',
            image: '/assets/workflow/image-to-video.jpg',
            alt: 'Image to video sample',
          },
          {
            id: 'spin',
            k: '09',
            label: '360 spins',
            short: 'Show a product from a rotational point of view',
            kicker: '360 SPINS',
            title: 'Rotational product view',
            body: 'Use a spin-style view to communicate shape and structure more clearly than one static angle.',
            image: '/assets/workflow/spins-360.jpg',
            alt: '360 spin sample',
          },
        ],
        metrics: [
          {
            value: '+20%',
            label: 'Conversion lift',
            body: 'Average conversion lift with richer visuals',
          },
          {
            value: '10x',
            label: 'Faster catalog refreshes',
            body: 'Faster catalog refreshes',
          },
          {
            value: '90%',
            label: 'Lower campaign lead time',
            body: 'Shorter seasonal campaign lead times',
          },
        ],
        outputRailLabel: 'Workflow output types',
        outputTags: ['Packshot', 'Staging', 'Variant', 'Close-up', 'Infographic', 'Motion'],
        selectorFootnote: 'Choose a challenge on the left to preview the output in the center and frame the operational upside on the right.',
        selectorCallout: 'result-first workflow',
      },
      showcase: {
        eyebrow: 'SHOWCASE · EXPERT HOOK',
        titleLines: ['Want content like this,', 'but not sure where to start?'],
        galleryLabel: 'ATELA example work gallery',
        cards: [
          {
            id: 'pdp',
            size: 'hero',
            kicker: 'PDP REFRESH',
            accentLabel: 'TEXT SAFE',
            accent: '#C6FF3D',
            title: 'Product detail page refresh',
            body: 'Sharper product-detail layouts that keep text, packaging, and brand information intact.',
            image: '/assets/hero-demo/drg/bg.avif',
            alt: 'ATELA product detail page refresh showcase',
            tags: ['PDP', 'Detail', 'Brand'],
          },
          {
            id: 'ads',
            size: 'side',
            kicker: 'PERFORMANCE ADS',
            accentLabel: 'CTR READY',
            accent: '#FF3DA8',
            title: 'Performance creative',
            body: 'Fast-turn Meta and TikTok ad variants designed for iteration, not one-off mockups.',
            image: '/assets/hero-demo/chamo/bg.avif',
            alt: 'ATELA performance ad creative showcase',
            tags: ['Ads', 'A/B Test', 'Campaign'],
          },
          {
            id: 'lifestyle',
            size: 'side',
            kicker: 'LIFESTYLE VISUAL',
            accentLabel: 'BRAND MOOD',
            accent: '#6B3DFF',
            title: 'Lifestyle showcase',
            body: 'Commerce imagery that keeps the brand mood intact while making the product feel buyable.',
            image: '/assets/hero-demo/lamp/bg.avif',
            alt: 'ATELA lifestyle commerce showcase',
            tags: ['Lifestyle', 'Mood', 'Campaign'],
          },
          {
            id: 'motion',
            size: 'wide',
            kicker: 'MOTION / VIDEO',
            accentLabel: 'LAUNCH PACK',
            accent: '#FFB020',
            title: 'Short-form motion pack',
            body: 'Short launch and retargeting clips that can extend a PDP story into motion without a separate production loop.',
            image: '/assets/hero-demo/pilot_trunk/bg.avif',
            alt: 'ATELA motion and video showcase',
            tags: ['Motion', 'Reels', 'Video'],
          },
        ],
        footnote: 'Pick the output format you want, and ATELA matches the right specialist on a per-project basis.',
        footCallout: 'Project-based · no lock-in',
      },
      marketplace: {
        eyebrow: 'EXPERT MARKETPLACE',
        titlePrefix: 'When you need AI experts,',
        titleHighlight: 'on-demand',
        titleSuffix: '.',
        lede: 'Product visuals and Instagram ads are different crafts. ATELA matches the right AI creator to each project and passes brand context through the platform. ',
        ledeStrong: 'No six-month lock-ins.',
        countLabelSuffix: ' experts',
        availability: 'available',
        projectsSuffix: 'projects',
        rateSuffix: '/ project',
        railHeading: '',
        railCount: '',
        railCta: 'View full roster →',
        specialties: [
          { k: '01', title: 'Performance Creative', desc: 'Meta, TikTok, and Kakao ads with CTR-driven iteration.', tags: ['Ads', 'A/B test'], color: '#FF3DA8', count: 42 },
          { k: '02', title: 'Product Visual', desc: 'PDP images, model shots, and cutouts built for commerce specs.', tags: ['Cutout', 'PDP'], color: '#C6FF3D', count: 68 },
          { k: '03', title: 'Instagram / Reels', desc: '15-second Reels and carousels tuned for Gen Z brands.', tags: ['Reels', 'Short-form'], color: '#6B3DFF', count: 31 },
          { k: '04', title: 'Brand Campaign', desc: 'Seasonal campaigns, lookbooks, and editorial systems.', tags: ['Editorial'], color: '#E8D5B0', count: 24 },
          { k: '05', title: 'Motion / Video', desc: 'Product motion, TVCs, and 3D product storytelling.', tags: ['Motion', '3D'], color: '#FFB020', count: 19 },
          { k: '06', title: 'Localization', desc: 'AI designers localized for Japan, the US, and SEA markets.', tags: ['JP', 'US', 'SEA'], color: '#3DA8FF', count: 15 },
        ],
        flow: [
          { step: '1', title: 'Upload a brief', body: 'Product, channel, tone, budget. 2 minutes.' },
          { step: '2', title: 'Get 3 AI matches', body: 'Ranked by specialty, track record, and availability.' },
          { step: '3', title: 'Run it project-by-project', body: 'ATELA passes along the brand assets and guidelines automatically.' },
          { step: '4', title: 'Delivery within 48 hours', body: 'Average turnaround, with unlimited revisions.' },
        ],
        motionPills: [
          'Ad Creative',
          'Social Assets',
          'Video Production',
          'Photography',
          'Motion Graphics',
          'Presentations',
          'Web & UI Design',
          'OOH & Fake OOH',
          'Illustration',
          'Email Design',
          'Brand Strategy',
          '3D Design',
          'Copywriting',
          'AI Consulting',
          'Campaign Development',
          'AI-Enhanced Creative',
          '...and more',
        ],
        experts: [
          { n: 'Suhyun Lee', h: 'S', r: 4.9, proj: 127, spec: 'Performance · Beauty', rate: 'KRW 480k+', color: '#FF3DA8' },
          { n: 'Junho Park', h: 'J', r: 4.8, proj: 89, spec: 'Product Visual · F&B', rate: 'KRW 360k+', color: '#C6FF3D' },
          { n: 'Jiwon K.', h: 'J', r: 5.0, proj: 64, spec: 'Motion · Fashion', rate: 'KRW 720k+', color: '#6B3DFF' },
          { n: 'Mina Choi', h: 'M', r: 4.9, proj: 156, spec: 'Reels · Gen Z Brand', rate: 'KRW 540k+', color: '#E8D5B0' },
        ],
      },
      compare: {
        eyebrow: 'WHY ATELA',
        titlePrefix: 'A new option beyond',
        titleHighlight: 'in-house, agencies, and freelancers.',
        dims: ['Speed', 'Flexibility', 'Quality', 'Scalability', 'Efficiency', 'Strategy'],
        rows: [
          { n: 'ATELA', d: 'AI tools and expert matching on one platform.', v: [1, 1, 1, 1, 1, 1], on: true },
          { n: 'In-house Team', d: 'In-house designers with limited bandwidth and specialties.', v: [0, 1, 1, 0, 0, 0] },
          { n: 'Creative Agency', d: 'Agency contracts that are slow, expensive, and rigid.', v: [0, 0, 1, 0, 0, 0] },
          { n: 'Freelancer', d: 'Freelancers with quality variance and limited scale.', v: [0, 1, 0, 0, 0, 0] },
          { n: 'AI Tools only', d: 'MJ and DALL·E without brand context.', v: [1, 0, 0, 1, 1, 0] },
        ],
      },
      caseStudy: {
        badge: 'Beauty brand · MUSINSA',
        eyebrow: 'CASE STUDY · Beauty Brand A',
        titlePrefix: 'Zero shoots, season collection',
        titleHighlight: 'launched.',
        body: 'This team used to spend three days on shooting and retouching for every new product. After connecting Cafe24 and adopting ATELA Growth, they generated 35 PDP visuals in an average of 14 minutes and iterated on performance creative with AI specialists twice a week. Weekly new-product uploads jumped from 4 to 28.',
        quote: 'We run seasonal campaigns without a shoot crew. Brand tone is actually more consistent now. We only bring in outside specialists for ad creative, and we do the rest in-platform.',
        cite: 'Brand manager, Company A',
        stats: [
          { value: '82%', label: 'lower shoot cost' },
          { value: '7×', label: 'weekly uploads' },
          { value: '+38%', label: 'ad CTR' },
        ],
        cta: 'Read more case studies →',
      },
      pricing: {
        eyebrow: 'PRICING',
        title: 'From Starter to Business, with lower Annual pricing.',
        billingAriaLabel: 'Select billing period',
        billingMonthly: 'Monthly',
        billingAnnual: 'Annual',
        billingBadge: '30% OFF',
        toolsTiers: [
          {
            name: 'Starter',
            features: ['200 credits / month', 'Selected models only', '4 parallel image generations', 'Core workflow'],
            prices: {
              monthly: { prefix: '$', amount: '19', suffix: '/mo', note: 'Base price' },
              annual: { prefix: '$', amount: '19', suffix: '/mo', note: 'Same on Annual' },
            },
          },
          {
            name: 'Creator',
            features: ['1,000 credits / month', 'Access to all models', '8 parallel image generations', '365-day favorite unlimited'],
            prices: {
              monthly: { prefix: '$', amount: '59', suffix: '/mo', note: 'Billed monthly' },
              annual: { prefix: '$', amount: '39', suffix: '/mo', originalAmount: '59', note: 'Billed annually' },
            },
          },
          {
            name: 'Growth',
            badge: 'Most Popular',
            features: ['3,000 credits / month', 'All models + priority queue', 'API + custom presets', 'One unlimited video model'],
            prices: {
              monthly: { prefix: '$', amount: '129', suffix: '/mo', note: 'Billed monthly' },
              annual: { prefix: '$', amount: '99', suffix: '/mo', originalAmount: '129', note: 'Billed annually' },
            },
            dark: true,
            featured: true,
          },
          {
            name: 'Business',
            badge: 'Best Value',
            features: ['1,500 credits per seat / month', '2-15 members shared workspace', 'Shared credit pool', 'Priority support + analytics'],
            prices: {
              monthly: { prefix: '$', amount: '89', suffix: '/seat/mo', note: '2-seat minimum' },
              annual: { prefix: '$', amount: '59', suffix: '/seat/mo', originalAmount: '89', note: '2-seat minimum, billed annually' },
            },
          },
        ],
        marketTitle: 'Need an AI specialist?',
        marketSubtitle: 'A secret weapon you pull out only when you need it.',
        marketRows: [
          { label: 'Performance Creative', value: '$349+' },
          { label: 'PDP Refresh (1 PDP)', value: '$259+' },
          { label: 'Instagram Reels 15s', value: '$399+' },
          { label: 'Lookbook Sprint (20 looks)', value: '$899+' },
          { label: 'Motion · Video', value: '$529+' },
        ],
        guarantee: 'Fixed scope · fast turnaround',
        subnote: 'No retainer · no lock-in',
      },
      finalCta: {
        eyebrow: 'START TODAY',
        titleLines: ['Connect products today,', 'wake up to 50 images + expert matches tomorrow.'],
        body: 'Start with Starter, or try Growth for 14 days. No credit card required.',
        primaryCta: 'Start trial →',
        secondaryCta: 'Talk to sales ↗',
      },
      footer: {
        description: 'AI creative platform built to preserve text, logos, and product detail. Team from Yonsei Univ. CV Lab. Seoul, South Korea.',
        platformTitle: 'Platform',
        platformLinks: {
          tech: 'Text Preservation',
          integrations: 'Workflow',
          marketplace: 'Experts',
        },
        companyTitle: 'Company',
        companyLinks: ['About', 'Team · Research', 'Blog', 'Careers'],
        supportTitle: 'Support',
        supportLinks: ['Docs · API', 'Community', 'Contact', 'Status'],
        bottomLeft: '© 2026 ATELA Inc. · Business registration 000-00-00000',
        bottomRight: 'Terms · Privacy · Cookies',
      },
    },
  };

  function getLocale() {
    if (window.atelaGetCurrentLocale) return window.atelaGetCurrentLocale();
    return 'ko';
  }

  function getCopySection(section) {
    const locale = getLocale();
    return COPY[locale]?.[section] || COPY.ko[section];
  }

  function syncPageMeta() {
    const page = getCopySection('page');
    if (!page) return;

    document.title = page.title;

    let description = document.querySelector('meta[name="description"]');
    if (!description) {
      description = document.createElement('meta');
      description.name = 'description';
      document.head.appendChild(description);
    }

    description.content = page.description;
  }

  window.ATELA_COPY = COPY;
  window.atelaGetCopySection = getCopySection;
  window.atelaSyncPageMeta = syncPageMeta;

  syncPageMeta();
})();
